sudo: required
services:
  - docker

before_install:
  - docker build -t jingli666/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jingli666/docker-react npm test -- --coverage

after_success:
  - docker build -t jingli666/multi-client ./client
  - docker build -t jingli666/multi-nginx ./nginx
  - docker build -t jingli666/multi-server ./server
  - docker build -t jingli666/multi-worker ./worker

# Log in to docker CLI
  - echo $"DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push jingli666/multi-client
  - docker push jingli666/multi-nginx
  - docker push jingli666/multi-server
  - docker push jingli666/multi-worker